package controller;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

import com.opencsv.CSVReader;

import model.Category;
import model.Compound;
import model.Country;
import model.Drug;
import model.Manufacturer;
import util.IDGenerator;

public class CSVDataReader {
	protected ArrayList<Drug> drugsList = new ArrayList<Drug>();
	protected ArrayList<Compound> compoundList = new ArrayList<Compound>();
	protected ArrayList<Manufacturer> manufacturerList = new ArrayList<Manufacturer>();
	protected ArrayList<Category> categoryList = new ArrayList<Category>();
	protected IDGenerator idCompoundGenerator = new IDGenerator();
	protected IDGenerator idCategoryGenerator = new IDGenerator();
	
	public boolean loadData(String path) throws FileNotFoundException {
	    CSVReader reader = new CSVReader(new FileReader(path),'\t','\"',1);

	    try {
	        String[] line;
	        
	        while ((line = reader.readNext()) != null) {      
	        	String drugCode = line [5];
	        	String compoundName = line[0];
	        	String brandName = line[6];
	        	String strength = line[10];
	        	String manufacturerId = line[1]; // It should be automatically generated by the application to avoid conflict of different resources with same id, or should use the country abbreviation concatenated 
	        	String manufacturerName = line[2];
	        	String categoryName = line[12];
	        	Compound compound = null;
	        	Manufacturer manufacturer = null;
	        	Category category = null;
	        	
	        	Country country = new Country(55,"Brazil", "BR"); //It should be passed as parameter 
	        	

	  	
	        	//Checking if the compound of the drug of the current line from the CSV is already on the list
	        	//In case it's not, add the new compound on it
	        	CompoundController compoundController = new CompoundController();
	        	
	        	if (this.compoundList != null && this.compoundList.size() != 0) {
	        		compound = compoundController.findCompound(compoundName, this.compoundList);
	        	}        	
	        	
	        	if (compound == null) {
	        		
	        		compound = new Compound(this.idCompoundGenerator.newId(), compoundName, null);
	        		this.compoundList.add(compound);
	        	}       	
	        	
	        	//Checking if the manufacturer of the drug of the current line from the CSV is already on the list
	        	//In case it's not, add the new manufacturer on it
	        	ManufacturerController manufacturerController = new ManufacturerController();
	        	
	        	if (this.manufacturerList != null && this.manufacturerList.size() != 0) {
	        		manufacturer = manufacturerController.findManufacturer(manufacturerName, this.manufacturerList);
	        	}
	        	
	        	if (manufacturer == null) {
	        		manufacturer = new Manufacturer(manufacturerId,manufacturerName);
	        		this.manufacturerList.add(manufacturer);
	        	}
	        	
	        	//Checking if the category of the drug of the current line from the CSV is already on the list
	        	//In case it's not, add the new category on it
	        	CategoryController categoryController = new CategoryController();
	        	
	        	if (this.categoryList != null && this.categoryList.size() != 0) {
	        		category = categoryController.findCategory(categoryName, this.categoryList);
	        	}        	
	        	
	        	if (category == null) {
	        		
	        		category = new Category(this.idCategoryGenerator.newId(), categoryName);
	        		this.categoryList.add(category);
	        	}      
	        	
	        	
	        	//Creatig istance of drug	        	
	        	Drug drug = new Drug(drugCode, brandName,null,strength,manufacturer,country,compound,category);
	           	this.drugsList.add(drug);
       	
	        }
	        
	        reader.close();
	        return true;
	    } catch (IOException e) {
	        e.printStackTrace();
	        return false;
	    }
	}
}

